### ISSUE TITLE
can't view docs file, md,txt files ok

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-seafile#9]
IP:54.162.78.191

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [x] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot
![image](https://user-images.githubusercontent.com/43192516/116352237-711f4e00-a827-11eb-91e4-eef64fcee8a3.png)
![image](https://user-images.githubusercontent.com/43192516/116352308-8a27ff00-a827-11eb-8563-92134cc04583.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
cause by port 9003, can't connect to onlyoffice

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/116373389-de3edd80-a83f-11eb-9216-4ab07019a1b3.png)

docker error logs
```
[2021-04-28T08:40:03.828] [ERROR] nodeJS - dnsLookup error: hostname = seafile.example.com
Error: getaddrinfo ENOTFOUND seafile.example.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[2021-04-28T08:40:03.828] [WARN] nodeJS - checkIpFilter error: docId = 8b6c38c22a6eaa7b4807;url = http://seafile.example.com/onlyoffice/editor-callback/

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
Flushing stats at  Wed Apr 28 2021 08:40:05 GMT+0000 (Coordinated Universal Time)
{ counters:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  timers: {},
  gauges: {},
  timer_data: {},
  counter_rates:
   { 'statsd.bad_lines_seen': 0,
     'statsd.packets_received': 0,
     'statsd.metrics_received': 0 },
  sets: {},
  pctThreshold: [ 90 ] }
```

**Comment by chendelin1982** [comment]
```
[root@ip-172-31-43-22 onlyofficedocs]# docker logs onlyoffice-docs
 * Starting PostgreSQL 12 database server                                [ OK ]
 * Starting RabbitMQ Messaging Server rabbitmq-server                    [ OK ]
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron                              [ OK ]
 * Starting nginx nginx                                                  [ OK ]
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx                                   [ OK ]
==> /var/log/onlyoffice/documentserver/converter/err.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2021-04-28T09:47:46.065] [WARN] nodeJS - update cluster with 1 workers
[2021-04-28T09:47:46.084] [WARN] nodeJS - worker 824 started.
[2021-04-28T09:47:46.091] [WARN] nodeJS - update cluster with 1 workers
[2021-04-28T09:48:32.873] [WARN] nodeJS - update cluster with 1 workers
[2021-04-28T09:48:32.881] [WARN] nodeJS - worker 932 started.
[2021-04-28T09:48:32.884] [WARN] nodeJS - update cluster with 1 workers

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
Error: getaddrinfo ENOTFOUND seafile.example.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[2021-04-28T09:48:16.322] [WARN] nodeJS - checkIpFilter error: docId = 8b6c38c22a6eaa7b4807;url = http://seafile.example.com/onlyoffice/editor-callback/
[2021-04-28T09:48:31.442] [WARN] nodeJS - Express server starting...
[2021-04-28T09:48:31.452] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-04-28T09:48:31.575] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.2.2. Build: 21
[2021-04-28T09:48:34.906] [ERROR] nodeJS - dnsLookup error: hostname = seafile.example.com
Error: getaddrinfo ENOTFOUND seafile.example.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[2021-04-28T09:48:34.906] [WARN] nodeJS - checkIpFilter error: docId = db75910a5d5fe9b095ce;url = http://seafile.example.com/onlyoffice/editor-callback/

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
28 Apr 09:47:45 - [759] reading config file: ./config/config.js
28 Apr 09:47:45 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/err.log <==

==> /var/log/onlyoffice/documentserver/spellchecker/out.log <==
[2021-04-28T09:47:45.936] [WARN] nodeJS - start cluster with 1 workers
[2021-04-28T09:47:45.951] [WARN] nodeJS - worker 817 started.
[2021-04-28T09:47:47.259] [WARN] nodeJS - Express server starting...
[2021-04-28T09:47:47.364] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode

==> /var/log/onlyoffice/documentserver/nginx.error.log <==
2021/04/28 09:49:48 [error] 5697#5697: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 175.11.28.181, server: , request: "GET /example/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "54.162.78.191:9002", referrer: "http://54.162.78.191:9002/welcome/"
2021/04/28 09:49:48 [error] 5697#5697: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 175.11.28.181, server: , request: "GET /example/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "54.162.78.191:9002", referrer: "http://54.162.78.191:9002/welcome/"
2021/04/28 09:49:52 [error] 5697#5697: *16 no live upstreams while connecting to upstream, client: 175.11.28.181, server: , request: "GET /example/ HTTP/1.1", upstream: "http://example/", host: "54.162.78.191:9002"

```

**Comment by chendelin1982** [comment]
modify
![image](https://user-images.githubusercontent.com/16741975/116387610-8c9d4f80-a84d-11eb-9941-c1c7782ebdb0.png)

then it ok
![image](https://user-images.githubusercontent.com/16741975/116386023-fc123f80-a84b-11eb-9eb6-5065666eb1c2.png)

**Comment by zengxc-1996** [comment]
Change this  /data/wwwroot/seafile/volumes/seafile_data/seafile/conf/ccnet.conf:
seafile.example.com to $public_ip:9100
Problem solved.

**Comment by qiaofeng1227** [comment]
Done
